#ifndef LIBQTCEREBELLUM_GLOBAL_H
#define LIBQTCEREBELLUM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQTCEREBELLUM_LIBRARY)
#  define LIBQTCEREBELLUMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBQTCEREBELLUMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQTCEREBELLUM_GLOBAL_H
